- hosts: all
  become: false
  tasks:
    - name: Run XYZ Tech on container
      docker_container:
        name: xyz_tech
        image: anouar009/xyz_tech:latest
        state: started
        auto_remove: true
        ports:
          - "8081:8081"