- name: Deploy XYZ Tech application on Kubernetes
  hosts: localhost
  vars:
    k8s_auth_kubeconfig: /var/lib/jenkins/.minikube/config 
  tasks:
    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'deployment.yml') }}"
    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'service.yml') }}"
