apiVersion: v1
kind: Service
metadata:
  name: xyz-tech-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: xyz-tech
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 308007
